### PR TITLE
Because of lazy devs with dumb whitespace on the end ot the message

### PR DESCRIPTION
**Pull request by kolaCZek**

### CODE REVIEW

**Comment by matthiasr** [comment]
Does Graphite accept these lines? If so, the devs are not lazy, the exporter is wrong. If not, we don't need to accept them either …

**Comment by kolaCZek** [comment]
In fact, it works with Graphite v. 0.9.15.

**Comment by matthiasr** [comment]
In that case, the change is correct. However, I don't like the tone of the commit message. Could you please amend it to remove "lazy" and "dumb"? It's really not their fault to assume that the exporter would accept what Graphite accepts.

**Comment by matthiasr** [comment]
(it seems I can't reopen this because the underlying branch is gone, so if you still want this please open a new PR)

**Comment by kolaCZek** [comment]
Ok, thanks...

**Pull request closed without merging**
