### PR TITLE
Bump client_golang v1.5.1

### PR DESCRIPTION
**Pull request by nvtkaszpir**
Should potentially fix issues with erros in prometheus client when
connection is terminated in the middle of the scraping request.

Example log error:

... http: superfluous response.WriteHeader call from
github.com/prometheus/client_golang/prometheus/promhttp.(*responseWriterDelegator).WriteHeader
(delegator.go:59)

See github issue #123 

Signed-off-by: Michał Sochoń <kaszpir@gmail.com>

### CODE REVIEW

**Comment by kpucynski** [comment]
If you are doing it already maybe bump it to the upstream 1.6? :)

**Comment by nvtkaszpir** [comment]
> If you are doing it already maybe bump it to the upstream 1.6? :)

maybe in another PR ;)

**Comment by nvtkaszpir** [comment]
If anyone willing to test the docker image `docker pull quay.io/kaszpir/graphite_exporter:bump-deps-151`

**Comment by matthiasr** [comment]
Wonderful, thank you!

**Pull request merged**
