### PR TITLE
Switch to sync.Map to improve performance when under lots of load

### PR DESCRIPTION
**Pull request by GiedriusS**
Part of https://github.com/prometheus/graphite_exporter/issues/66. The idea behind this change is to lock the map per key but not per the whole instance.
Also, switch a few methods so that there would be no copying of `sync.Map`. That might have improved the performance as well because there are less map copying.

After:
[profilev2.pdf](https://github.com/prometheus/graphite_exporter/files/2653061/profilev2.pdf)

Before:
[profiling_output.pdf](https://github.com/prometheus/graphite_exporter/files/2653062/profiling_output.pdf)

I don't have the graphs for lengths of how long it took to download `/metrics` with ~500k metrics but now it seems that the lengths are much more consistent even though they still take a long time. It used to jump from ~2s. to ~30s. With this change it consistently takes around ~10s. which would you expect to happen since the stress testing program pushes new metrics each 10 seconds.

### CODE REVIEW

**Comment by matthiasr** [comment]
Hmm, I'm not sure going from 2s to 10s in the base case is really an improvement, especially since 10s is already the default scrape timeout.

Is locking per key beneficial for the scrape case that needs to look at all the values anyway?

What if we change the Mutex to an RWMutex but use a regular map? Would that help?

Could you also post flame graphs? I find them easier to read for "where is time being spent".

**Comment by GiedriusS** [comment]
My point was that having a consistent ~10s. delay is better than having a delay that jumps anywhere from 2 s. to even 30 s. because the user then would know for sure that something is wrong. Even I myself got tricked into believing that everything is OK because I refreshed when that scrape had happened successfully due to pure luck. `sync.Map` already uses a Mutex underneath that is only held when necessary: https://golang.org/src/sync/map.go?s=1149:2596#L17 so essentially we would be reinventing the wheel here, IMHO. I will post the flame graphs when I can but please consider this again.

**Comment by matthiasr** [comment]
I agree that the current status is not great, but if the baseline is 2 seconds, I would rather not 5-times that. This points at some new overhead that we are introducing and that I would like to avoid as much as possible.

I am not claiming that an RWMutex would do better but I think it's worth trying. I don't think moving from a Mutex to an RWMutex is reinventing anything.

Could you share your test program?

**Comment by matthiasr** [comment]
I'm going to close this because the mainline code has changed a ton, including significant performance improvements from the `client_golang` update.

Please benchmark again, and open a new PR if we still have significant potential for improvement.

**Pull request closed without merging**
