### PR TITLE
Serialize processing of samples

### LINKED ISSUE #90: New glob matcher report invalid values.
We're testing both `0.5.0` and `0.4.2` and getting errors with the new glob matcher.

With `0.5.0`, graphite exporter error out with duplicated metrics error

    collected metric "flink_assigned_partitions" { label:<name:"job" value:"ebs-dumper" > label:<name:"operator" value:"Source:-kafka:-ebs-umts" > label:<name:"subtask" value:"0" > label:<name:"task" value:"Source:-kafka:-ebs-umts-->-Process-ebs-umts-events" > gauge:<value:487941.72 > } was collected before with the same name and label values

The weird part is we don't know where the value `487941.72` comes from. We never sent that value and it didn't show up in the debug log either.

With version `0.4.2`, the graphite_exporter doesn't error, but reports both valid and invalid values, which screws up the monitoring process.

    flink_assigned_partitions{job="ebs-dumper",operator="Source:-kafka:-ebs-lte",subtask="2",task="Source:-kafka:-ebs-lte-->-Process-ebs-lte-events"} 5
    flink_assigned_partitions{job="ebs-dumper",operator="Source:-kafka:-ebs-lte",subtask="2",task="Source:-kafka:-ebs-lte-->-Process-ebs-lte-events"} 1.80102799e+06

Reverting back to `0.3.0` or using the `regex` matcher will avoid this issue.

This might relate to issues #79

### PR DESCRIPTION
**Pull request by matthiasr**
Fixes #90.

`mapper.GetMapping` is not safe for concurrent access:

```
==================
WARNING: DATA RACE
Write at 0x00c000190100 by goroutine 40:
  github.com/prometheus/graphite_exporter/vendor/github.com/prometheus/statsd_exporter/pkg/mapper.(*MetricMapper).GetMapping()
      /Users/mr/src/github.com/prometheus/graphite_exporter/vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go:222 +0x9a9
  main.(*graphiteCollector).processLine()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:118 +0x1d8
  main.(*graphiteCollector).processReader()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:104 +0x103

Previous write at 0x00c000190100 by goroutine 39:
  github.com/prometheus/graphite_exporter/vendor/github.com/prometheus/statsd_exporter/pkg/mapper.(*MetricMapper).GetMapping()
      /Users/mr/src/github.com/prometheus/graphite_exporter/vendor/github.com/prometheus/statsd_exporter/pkg/mapper/mapper.go:222 +0x9a9
  main.(*graphiteCollector).processLine()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:118 +0x1d8
  main.(*graphiteCollector).processReader()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:104 +0x103

Goroutine 40 (running) created at:
  main.main.func2()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:293 +0x1db

Goroutine 39 (finished) created at:
  main.main.func2()
      /Users/mr/src/github.com/prometheus/graphite_exporter/main.go:293 +0x1db
==================
```

The statsd exporter does all processing in a single goroutine, so the
graphite exporter should too, at least until/unless we can make the
mapper reentrant.

@fffonion is `GetMapping` meant to be called concurrently? could it be?

### CODE REVIEW

**Comment by matthiasr** [comment]
@kien-truong I would like to use your test case for this, but the commit is missing the DCO sign-off. Could you please follow the instructions in https://github.com/prometheus/graphite_exporter/pull/94/checks?check_run_id=139346580 on your branch? Then I can rebase this in.

**Comment by kien-truong** [comment]
Hi, I've add the signed-off.

**Comment by matthiasr** [comment]
thanks! would you mind reviewing the fix? I can merge my changes but I would prefer if someone else also says that they're sensible.

**Comment by kien-truong** [comment]
The changes look good to me. Thanks.

**Pull request merged**
